---
title: "Data Analysis Workflow Example on Your Data (UMAP, FlowSOM, MEM)"
author: "Copyright (c) 2016-2019 by Kirsten Diggins, Sierra Barone, and Jonathan Irish, All Rights Reserved; see EULA-MEM.text for MEM license information"
date: "July 2019"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---
```{r setup, include=FALSE}
library(tictoc)
tic()
# Load all libraries
# If you get an error message, you will need to try re-installing packages
library(FlowSOM)
library(flowCore)
library(Biobase)
library(gplots)
library(ggplot2)
library(hexbin)
library(MEM)
library(tidyverse)
library(Rtsne)
library(uwot)
library(viridis)
library(ggExtra)
library(RColorBrewer)

choose.markers <- function(exp_data) {
    print("Numbered column names, in order they appear in file: ")
    print(paste(c(1:(ncol(exp_data))), ": ", 
                colnames(exp_data[, c(1:(ncol(exp_data)))]), sep = ""))
    markers = readline("Enter column numbers to include (e.g. 1:5,6,8:10).\n")
    sep_vals = unlist(strsplit(markers, ","))
    list_vals = vector()
    for (i in 1:length(sep_vals)) {
        val = sep_vals[i]
        if (length(unlist(strsplit(val, ":"))) > 1) {
            new_val = as.numeric(unlist(strsplit(val, ":"))[1]):as.numeric(unlist(strsplit(val, ":"))[2])
        } else{
            new_val = as.numeric(sep_vals[i])
        }
        list_vals = c(list_vals, new_val)
    }
    markerList = c(list_vals)
    return(markerList)
}
```

```{r read_data_files, warning=FALSE}
# read FCS files into R; make sure FCS files are in the my_data_files
setwd("/Users/Caroline/Desktop/BMIF6310 project/Rdata")
my.files <-  dir(pattern = "*.csv")

my.data <- read.csv(my.files,header = T,skip=1,check.names = F)

umap.markers <- my.data %>%
  select(contains("CD"),contains("HLA"))
```

```{r select_and_scale}
# set the cofactor
cofactor = 5

# if all of your channels have the same cofactor 
my.markers.transformed <- umap.markers %>%
  mutate_all(function(x)
    asinh(x / 5))

my.data.sampled = sample_n(my.markers.transformed,8000)
```
```{r run_UMAP}
tic()
# Run UMAP on chosen markers
# select all channels to use in UMAP by opening console below
myumap <- umap(my.data.sampled, 
               ret_model = TRUE, 
               verbose = TRUE,n_neighbors = 15,min_dist = 0.2,n_components = 2,metric = "euclidean")
toc()
umap.data = as.data.frame(myumap$embedding)

range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1]/range[2])

# UMAP flat dot plot and density dot plot
UMAP.plot <- data.frame(x = umap.data[,1], y = umap.data[,2])

ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + geom_point(aes(x=x, y=y), cex = 1) + labs( x = "UMAP 1", y = "UMAP 2") + theme_bw()

ggplot(UMAP.plot, aes(x=x, y=y)) + coord_fixed(ratio = graphical.ratio)  + geom_bin2d(bins = 128) + 
  scale_fill_viridis_c(option = "A", trans = "sqrt") + scale_x_continuous(expand = c(0.1,0)) + 
  scale_y_continuous(expand = c(0.1,0)) + labs(x = "UMAP 1", y = "UMAP 2") + theme_bw()
```


```{r FlowSOM on UMAP}
# enter target number of clusters
target.clusters = 5

# Run FlowSOM on your selected variable
flowsom.input = umap.data
mat <- as.matrix(flowsom.input)

# create flowFrame
metadata <-
  data.frame(name = dimnames(mat)[[2]],
             desc = dimnames(mat)[[2]])
metadata$range <- apply(apply(mat, 2, range), 2, diff)
metadata$minRange <- apply(mat, 2, min)
metadata$maxRange <- apply(mat, 2, max)
input.flowframe <- new("flowFrame",
                      exprs = mat,
                      parameters = AnnotatedDataFrame(metadata))
tic()
# implement the FlowSOM on the data
fsom <-
  FlowSOM(
    input.flowframe,
    compensate = FALSE,
    transform = FALSE,
    toTransform = c(1:2),
    scale = TRUE,
    colsToUse = c(1:2),
    nClus = target.clusters,
    seed = 1
  )
toc()
FlowSOM.clusters <-
  as.matrix(fsom[[2]][fsom[[1]]$map$mapping[, 1]])

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, 
                           rownames(qual_col_pals)))
col_vector = col_vector[-c(4,17,19,27,29:45)]
values = sample(col_vector)

# plot FlowSOM clusters on UMAP axes
ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + 
  geom_point(aes(x=x, y=y, color=FlowSOM.clusters),cex = 1.5) + 
  guides(colour = guide_legend(override.aes = list(size=5), nrow = 13)) +
  labs(x = "UMAP 1", y = "UMAP 2",title = "FlowSOM Clustering on UMAP Axes", 
       color = "FlowSOM Cluster") + theme_bw() + 
  scale_color_manual(values = values)  
cluster = as.numeric(as.vector((FlowSOM.clusters)))
data.to.export = cbind(my.data.sampled,umap.data,cluster)
write.csv(data.to.export,file = "data file with UMAP and FlowSOM.csv")
toc()
```

```#{r MEM on UMAP/FlowSOM Clusters}
Run MEM on the FlowSOM clusters from UMAP
cluster = as.numeric(as.vector((FlowSOM.clusters)))
cMEM.data = cbind(my.markers.transformed, cluster)

MEM.values.uf = MEM(
  MEM.data,
  transform = FALSE,
  cofactor = 0,
  choose.markers = FALSE,
  markers = "all",
  choose.ref = FALSE,
  zero.ref = FALSE,
  rename.markers = FALSE,
  file.is.clust = FALSE,
  add.fileID = FALSE,
  IQR.thresh = NULL
)

 build MEM heatmap and output enrichment scores
build.heatmaps(
  MEM.values.uf,
  cluster.MEM = "none",
  cluster.medians = "none",
  display.thresh = 1,
  newWindow.heatmaps = FALSE,
  output.files = FALSE,
  labels = FALSE,
  only.MEMheatmap = TRUE
)
```
